import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { TextInput } from 'react-native-paper';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useSelector } from 'react-redux';
import moment from 'moment';
import { COLORS, UI } from '../../assets/Colors';
import { hasPermission } from '../../utils/permissions';
import { socket } from '../../socket/socket';
import { fillGasPositionApi, getGasDashboardApi, receiveGasBottlesApi, startGasBottleApi, updateGasPositionWeightApi } from '../../api/gasManagementApi';

export default function GasManagementScreen({ navigation }) {
  const user = useSelector(state => state.auth.user); const client = useQueryClient();
  const canManage = hasPermission(user, 'gas.manage');
  const [dialog, setDialog] = useState(null);
  const [form, setForm] = useState({ bottle_count: '', rate_per_kg: '' });
  const [filledWeight, setFilledWeight] = useState('');
  const query = useQuery({ queryKey: ['gas-management'], queryFn: getGasDashboardApi });
  const summary = query.data?.data?.summary || {}; const positions = query.data?.data?.positions || [];
  useEffect(() => { const refresh = () => client.invalidateQueries({ queryKey: ['gas-management'] }); socket.on('gas_management_updated', refresh); return () => socket.off('gas_management_updated', refresh); }, [client]);
  const success = result => { setDialog(null); client.invalidateQueries({ queryKey: ['gas-management'] }); Alert.alert('Saved', result.message); };
  const failure = error => Alert.alert('Could not save', error?.response?.data?.message || 'Please try again.');
  const receive = useMutation({ mutationFn: receiveGasBottlesApi, onSuccess: result => { setForm({ bottle_count: '', rate_per_kg: '' }); success(result); }, onError: failure });
  const fill = useMutation({ mutationFn: ({ position, weight }) => fillGasPositionApi(position, weight), onSuccess: result => { setFilledWeight(''); success(result); }, onError: failure });
  const correctWeight = useMutation({ mutationFn: ({ position, weight }) => updateGasPositionWeightApi(position, weight), onSuccess: success, onError: failure });
  const start = useMutation({ mutationFn: startGasBottleApi, onSuccess: success, onError: failure });
  const busy = receive.isPending || fill.isPending || correctWeight.isPending || start.isPending;
  if (query.isLoading) return <View style={styles.center}><ActivityIndicator /></View>;
  return <><ScrollView style={styles.page} contentContainerStyle={styles.content}>
    <Text style={styles.title}>Gas Stock</Text><Text style={styles.muted}>Receive filled bottles and prepare GAS-1 to GAS-4.</Text>
    <View style={styles.grid}><View style={styles.metric}><Text style={styles.muted}>Filled bottles in plant</Text><Text style={styles.value}>{summary.filled_bottles || 0}</Text></View><View style={styles.metric}><Text style={styles.muted}>Current gas rate per kg</Text><Text style={styles.value}>₹{Number(summary.current_gas_rate || 0).toFixed(2)}</Text></View></View>
    <Text style={styles.muted}>Unassigned filled bottles: {summary.stored_filled_bottles || 0}</Text>
    <View style={styles.actions}>{canManage && <TouchableOpacity style={styles.button} onPress={() => setDialog({ type: 'receive' })}><Text style={styles.buttonText}>Add new bottle stock</Text></TouchableOpacity>}<TouchableOpacity style={styles.secondary} onPress={() => navigation.navigate('GasChangeMovements')}><Text style={styles.link}>Gas change movements</Text></TouchableOpacity></View>
    <View style={styles.positions}>{[1, 2, 3, 4].map(number => { const bottle = positions.find(item => Number(item.position_no) === number); return <TouchableOpacity key={number} disabled={!canManage} style={[styles.position, bottle?.status === 'running' && styles.running]} onPress={() => { setFilledWeight(bottle?.filled_weight_kg == null ? '' : String(bottle.filled_weight_kg)); setDialog({ type: 'position', number, bottle }); }}><Text style={styles.positionTitle}>GAS-{number}</Text><Text style={styles.positionStatus}>{bottle?.status === 'running' ? 'Running' : bottle?.status === 'ready' ? 'Ready to start' : 'Empty slot'}</Text><Text style={styles.muted}>{bottle ? `${bottle.bottle_code} · Filled weight: ${bottle.filled_weight_kg ?? 'Not set'} kg` : 'Tap to place a filled bottle'}</Text></TouchableOpacity>; })}</View>
  </ScrollView><Modal transparent visible={dialog !== null} animationType="fade" onRequestClose={() => !busy && setDialog(null)}><View style={styles.overlay}><View style={styles.modal}>
    {dialog?.type === 'receive' ? <><Text style={styles.heading}>Add new bottle stock</Text><TextInput mode="outlined" label="Number of bottles received" keyboardType="number-pad" value={form.bottle_count} onChangeText={value => setForm({ ...form, bottle_count: value })} /><TextInput mode="outlined" label="Rate per kg ₹" keyboardType="decimal-pad" value={form.rate_per_kg} onChangeText={value => setForm({ ...form, rate_per_kg: value })} /><Text style={styles.muted}>Nominal capacity: 425 kg. Price per bottle: ₹{(425 * Number(form.rate_per_kg || 0)).toLocaleString('en-IN', { maximumFractionDigits: 2 })}.</Text><TouchableOpacity style={styles.button} disabled={busy} onPress={() => receive.mutate({ bottle_count: Number(form.bottle_count), rate_per_kg: Number(form.rate_per_kg) })}><Text style={styles.buttonText}>{busy ? 'Saving…' : 'Add new bottle stock'}</Text></TouchableOpacity></>
      : <><Text style={styles.heading}>GAS-{dialog?.number}</Text>{dialog?.bottle ? <><Text style={styles.muted}>{dialog.bottle.bottle_code}</Text><TextInput mode="outlined" label="Filled bottle weight (kg)" keyboardType="decimal-pad" value={filledWeight} onChangeText={setFilledWeight} /><TouchableOpacity style={styles.secondary} disabled={busy} onPress={() => correctWeight.mutate({ position: dialog.number, weight: Number(filledWeight) })}><Text style={styles.link}>Save filled weight</Text></TouchableOpacity><Text style={styles.positionStatus}>{dialog.bottle.status}</Text>{dialog.bottle.status === 'ready' && !summary.running_bottle_number && <TouchableOpacity style={styles.button} disabled={busy} onPress={() => start.mutate({ position_no: dialog.number, started_at: moment().format('YYYY-MM-DD HH:mm:ss') })}><Text style={styles.buttonText}>{busy ? 'Starting…' : 'Start gas supply'}</Text></TouchableOpacity>}</> : <><Text style={styles.muted}>Place the next unassigned filled bottle in this slot.</Text><TextInput mode="outlined" label="Filled bottle weight (kg)" keyboardType="decimal-pad" value={filledWeight} onChangeText={setFilledWeight} /><TouchableOpacity style={styles.button} disabled={busy} onPress={() => fill.mutate({ position: dialog.number, weight: Number(filledWeight) })}><Text style={styles.buttonText}>{busy ? 'Saving…' : 'Save filled weight'}</Text></TouchableOpacity></>}</>}
    <TouchableOpacity style={styles.secondary} disabled={busy} onPress={() => setDialog(null)}><Text style={styles.link}>Close</Text></TouchableOpacity>
  </View></View></Modal></>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: COLORS.bg }, content: { padding: 18, gap: 14, paddingBottom: 80 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 26, fontWeight: '800', color: COLORS.text }, heading: { fontSize: 19, fontWeight: '700', color: COLORS.text }, muted: { color: COLORS.muted, lineHeight: 20 }, grid: { flexDirection: 'row', gap: 10 }, metric: { flex: 1, padding: 15, gap: 5, backgroundColor: COLORS.white, borderRadius: UI.radiusSmall }, value: { fontSize: 20, fontWeight: '800', color: COLORS.text }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, button: { backgroundColor: COLORS.accent, padding: 14, borderRadius: UI.radiusSmall, alignItems: 'center' }, buttonText: { color: COLORS.white, fontWeight: '700' }, secondary: { backgroundColor: COLORS.accentSoft, padding: 14, borderRadius: UI.radiusSmall, alignItems: 'center' }, link: { color: COLORS.accent, fontWeight: '700' }, positions: { gap: 10 }, position: { backgroundColor: COLORS.white, padding: 18, borderRadius: UI.radiusSmall, gap: 6, borderWidth: 1, borderColor: COLORS.border }, running: { borderColor: '#219b74', borderWidth: 2, backgroundColor: '#e9f8f2' }, positionTitle: { color: COLORS.accent, fontWeight: '800', fontSize: 15 }, positionStatus: { color: COLORS.text, fontSize: 20, fontWeight: '800' }, overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,.45)', justifyContent: 'center', padding: 20 }, modal: { backgroundColor: COLORS.white, borderRadius: UI.radius, padding: 20, gap: 14 } });
