import React,{useState}from'react';
import{ActivityIndicator,Alert,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useQuery}from'@tanstack/react-query';
import{useSelector}from'react-redux';
import DropDownPicker from'react-native-dropdown-picker';
import{getCurrentFinancialYearApi}from'../../api/financialYearsApi';
import{getMonthlyReportApi}from'../../api/monthlyReportApi';
import{COLORS,UI}from'../../assets/Colors';
import{hasPermission}from'../../utils/permissions';
import{centeredContent,useResponsive}from'../../utils/responsive';
import{downloadMonthlyReport}from'../../utils/serverMonthlyReport';

const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const indiaMonth=()=>new Date(Date.now()+330*60*1000).getUTCMonth()+1;
const num=value=>Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:3});
const money=value=>Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function MonthlyReportsScreen({navigation}){
 const user=useSelector(state=>state.auth.user);const canView=hasPermission(user,'monthly_reports.view');const canPdf=hasPermission(user,'monthly_reports.report');const{contentMaxWidth}=useResponsive();
 const[month,setMonth]=useState(indiaMonth);const[draft,setDraft]=useState(month);const[open,setOpen]=useState(false);const[generating,setGenerating]=useState(false);
 const yearQuery=useQuery({queryKey:['current-financial-year'],queryFn:getCurrentFinancialYearApi,enabled:canView,retry:false});const year=yearQuery.data?.data;
 const startYear=Number(year?.start_date?.slice(0,4));const items=year?.start_date?Array.from({length:12},(_,index)=>{const value=((index+3)%12)+1;return{value,label:`${MONTHS[value-1]} ${startYear+(value<4?1:0)}`};}):[];
 const query=useQuery({queryKey:['monthly-report',year?.id,month],queryFn:()=>getMonthlyReportApi({month,financial_year_id:year.id}),enabled:canView&&Boolean(year?.id),retry:false});const report=query.data?.data;
 const generate=async()=>{setGenerating(true);try{const pdf=await downloadMonthlyReport({month,financial_year_id:year.id});navigation.navigate('PdfViewer',{...pdf,title:`Monthly Report · ${report.period.label}`});}catch(error){Alert.alert('Could not generate PDF',error?.response?.data?.message||error?.message||'Please try again.');}finally{setGenerating(false);}};
 if(!canView)return<View style={styles.center}><Text style={styles.muted}>You do not have monthly reports access.</Text></View>;
 return<ScrollView style={styles.page} contentContainerStyle={[styles.content,centeredContent(contentMaxWidth)]}>
  <Text style={styles.title}>Monthly Reports</Text><Text style={styles.muted}>Complete historical production, zinc, Ash & Dross, planning, contractor, and expense report.</Text>
  {yearQuery.isLoading?<ActivityIndicator color={COLORS.accent}/>:yearQuery.isError?<Card><Text style={styles.error}>{yearQuery.error?.response?.data?.message||'Set a current financial year in Settings.'}</Text></Card>:<>
   <Card><Text style={styles.heading}>Financial year {year.financial_year}</Text><Text style={styles.muted}>Change the selected year from Settings › Financial Year.</Text><DropDownPicker open={open}setOpen={setOpen}value={draft}setValue={setDraft}items={items}listMode="MODAL"modalTitle="Select report month"style={styles.dropdown}/><TouchableOpacity style={styles.button}onPress={()=>{setMonth(draft);if(draft===month)query.refetch();}}><Text style={styles.buttonText}>Fetch Monthly Report</Text></TouchableOpacity></Card>
   {query.isLoading?<ActivityIndicator color={COLORS.accent}/>:query.isError?<TouchableOpacity style={styles.card}onPress={query.refetch}><Text style={styles.error}>{query.error?.response?.data?.message||'Could not load this monthly report. Tap to retry.'}</Text></TouchableOpacity>:report?<>
    <View style={styles.hero}><Text style={styles.heroLabel}>{report.period.label.toUpperCase()}</Text><Text style={styles.heroValue}>{num(report.production.total_ms_kg/1000)} ton</Text><Text style={styles.heroDetail}>MS production · {num(report.production.zinc_consumption_percent)}% zinc consumption after recovery</Text></View>
    <Section title="Production"><Grid data={[["MS production",`${num(report.production.total_ms_kg)} kg`],["GI production",`${num(report.production.total_gi_kg)} kg`],["Zinc used",`${num(report.production.net_zinc_kg)} kg`],["Production days",num(report.production.production_days)],["Entries",num(report.production.entry_count)],["Quantity",`${num(report.production.quantity)} NOS`]]}/></Section>
    <Section title="Zinc Stock"><Grid data={[["Opening plant",`${num(report.zinc.opening_plant_kg)} kg`],["Opening kettle",`${num(report.zinc.opening_kettle_kg)} kg`],["Purchased zinc",`${num(report.zinc.received_kg)} kg`],["Added to kettle",`${num(report.zinc.transferred_to_kettle_kg)} kg`],["Production use",`${num(report.zinc.production_used_kg)} kg`],["Closing plant",`${num(report.zinc.closing_plant_kg)} kg`],["Closing kettle",`${num(report.zinc.closing_kettle_kg)} kg`],["Stock corrections",num(report.zinc.corrections)]]}/></Section>
    <Section title="Ash & Dross"><Grid data={[["Ash collected",`${num(report.byproducts.ash_weight_kg)} kg`],["Dross collected",`${num(report.byproducts.dross_weight_kg)} kg`],["Recovered zinc",`${num(report.byproducts.recovered_zinc_kg)} kg`],["Value with GST",`₹${money(report.byproducts.total_with_gst)}`]]}/></Section>
    <Section title="Expense & Plant Cost"><Grid data={[["Total expense",`₹${money(report.expenses.totals.total_expense)}`],["Running plant cost",`₹${money(report.expenses.totals.running_plant_cost)}/kg`],["Average production/day",`${num(report.expenses.totals.average_ms_production_per_day_kg/1000)} ton`]]}/></Section>
    <Section title="Expense Breakdown">{Object.entries(report.expenses.expenses).map(([key,value])=><View key={key}style={styles.listRow}><Text style={[styles.muted,styles.flex]}>{key.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}</Text><Text style={styles.value}>₹{money(value)}</Text></View>)}</Section>
    <List title="Shift Production"rows={report.shifts}name="shift_name"/><List title="Material Production"rows={report.materials}name="material"/><List title="Contractor Production"rows={report.contractors}name="contractor_name"/>
    <Section title={`Planning (${report.planning.length})`}>{report.planning.length?report.planning.map(item=><View key={item.id}style={styles.listRow}><View style={styles.flex}><Text style={styles.heading}>{item.challan_no||'Challan'} · {item.party_name}</Text><Text style={styles.muted}>{item.material_description}</Text></View><Text style={styles.value}>{num(item.produced_qty)} / {num(item.planned_qty)} NOS</Text></View>):<Text style={styles.muted}>No planning activity for this month.</Text>}</Section>
    {canPdf&&<TouchableOpacity style={styles.pdfButton}disabled={generating}onPress={generate}>{generating?<ActivityIndicator color={COLORS.white}/>:<Text style={styles.buttonText}>Generate Complete PDF Report</Text>}</TouchableOpacity>}
   </>:null}
  </>}
 </ScrollView>;
}
function Card({children}){return<View style={styles.card}>{children}</View>;}function Section({title,children}){return<Card><Text style={styles.sectionTitle}>{title}</Text>{children}</Card>;}function Grid({data}){return<View style={styles.grid}>{data.map(([label,value])=><View key={label}style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>)}</View>;}function List({title,rows,name}){return<Section title={title}>{rows.length?rows.map((item,index)=><View key={`${item[name]}:${index}`}style={styles.listRow}><Text style={[styles.heading,styles.flex]}>{item[name]||'Unspecified'}</Text><Text style={styles.value}>{num(item.ms_kg)} kg MS</Text></View>):<Text style={styles.muted}>No records for this month.</Text>}</Section>;}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:COLORS.bg},content:{padding:18,gap:14,paddingBottom:60},center:{flex:1,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'700',color:COLORS.text},muted:{color:COLORS.muted,fontSize:13,lineHeight:20},heading:{color:COLORS.text,fontSize:15,fontWeight:'700'},sectionTitle:{color:COLORS.text,fontSize:18,fontWeight:'800'},card:{backgroundColor:COLORS.white,borderRadius:UI.radius,padding:18,gap:14},dropdown:{borderColor:COLORS.border},button:{backgroundColor:COLORS.accent,borderRadius:UI.radiusSmall,minHeight:48,alignItems:'center',justifyContent:'center',padding:12},buttonText:{color:COLORS.white,fontWeight:'700'},hero:{backgroundColor:COLORS.primary,borderRadius:UI.radiusLarge,padding:24,gap:6},heroLabel:{color:COLORS.onHero,fontSize:12,fontWeight:'700'},heroValue:{color:COLORS.white,fontSize:34,fontWeight:'800'},heroDetail:{color:COLORS.onHero,fontSize:13},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{flexBasis:145,flexGrow:1,backgroundColor:COLORS.surfaceMuted,borderRadius:UI.radiusSmall,padding:13,gap:5},metricValue:{color:COLORS.text,fontSize:17,fontWeight:'800'},listRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,borderBottomWidth:1,borderBottomColor:COLORS.border,paddingVertical:9},flex:{flex:1},value:{color:COLORS.primary,fontWeight:'700'},pdfButton:{backgroundColor:COLORS.primary,borderRadius:UI.radiusSmall,minHeight:52,alignItems:'center',justifyContent:'center'},error:{color:COLORS.danger,lineHeight:20}});
